spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
    web-application-type: none
  quartz:
    job-store-type: memory

# Agent configuration
# pingInterval: ping interval in ms.
agent:
  nodeName: batchmanager
  pingInterval: 300000
  performanceInterval: 60000
  docker:
    network: docker_default
    hostname:

# Kafka configuration.
# bootstrapAddress: Kafka server URL.
# maxRequestSize: Maximal request size (default: 4MB).
# retentionDays: Number of days the logs are kept.
# deletionDays: Number of days after which the logs are deleted.
# topic: Apache Kafka topic name.
kafka:
  bootstrapAddress: localhost:9092
  maxRequestSize: 4194304
  retentionDays: 1
  deletionDays: 1
  active: true
  agentCommand:
    offsetReset: latest
    topic: batchAgentCommand
    partitions: 1
    replicas: 1
  serverCommand:
    offsetReset: latest
    topic: batchServerCommand
    group: batchmanager
    partitions: 1
    replicas: 1
  jobStatus:
    offsetReset: latest
    topic: batchServerCommand
    group: batchmanager
    partitions: 1
    replicas: 1
